version: '2'
services:
    mongodb:
        image: amsys/mongo:v1
        container_name: mongodb
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
          - MONGODB_USER=amsys
          - MONGODB_PASS=amsys
        volumes:
          - ./data/db:/data/db
        restart: always
        ports:
            - 27018:27017
